### ISSUE TITLE
Why Navigation is empty and get children?

### ISSUE THREAD

**Issue by biapar** [vertica-as/Vertica.Umbraco.Headless#10]
I'm tring your packages to use U10 as data manager. I try to open the root node. 
Why the "navigation" is empty?
How to get children?

"navigation":{"breadcrumb":[]}

For example, this is a json of the blog node but there aren't listed the children.

{"alias":"articleList","content":{"mainContent":null,"title":"","subtitle":"Many blog posts for you","mainImage":{"name":"Desktop notebook glasses","width":1920,"height":1248,"extension":"jpg","additionalProperties":{},"url":"/media/uxcbvbvf/desktop-notebook-glasses.jpg","focalPoint":{"left":0.5,"top":0.5},"crops":[]},"metaName":"","metaDescription":"","metaKeywords":[],"umbracoNaviHide":false,"hideFromXMLSitemap":false},"metadata":{"name":"Blog","url":"https://localhost:44303/blog/","id":"31523089-f648-4883-9087-ef9a0b83129f","languages":[]},"navigation":{"breadcrumb":[{"name":"Home","url":"/"}]}}

**Comment by janus-toendering** [comment]
The [navigation](https://github.com/vertica-as/Vertica.Umbraco.Headless/blob/main/docs/exploring-the-json-format.md#navigation) property defaults to providing a breadcrumb (ie. ancestors not children). 

There is a document describing how to override the default behaviour here:
https://github.com/vertica-as/Vertica.Umbraco.Headless/blob/main/docs/customizing-the-page-json-output.md
